### ISSUE TITLE
Error on loading addon

### ISSUE THREAD

**Issue by xuv** [folkertdev/freestyle-svg-exporter#4]
Hello @folkertdev 

I've just downloaded the latest version of the script and I run into an error.
The addon does not want to load. Here is the error: 

```
Traceback (most recent call last):
  File "/usr/share/blender/2.74/scripts/modules/addon_utils.py", line 306, in enable
    mod = __import__(module_name)
  File "/usr/share/blender/2.74/scripts/addons/render_freestyle_svg.py", line 52, in <module>
    from freestyle.utils import (
ImportError: cannot import name 'BoundingBox'
```

Maybe it was a bad call for me to pull it from the repo again.

Here is my version of Blender:

```
Blender 2.74 (sub 0)
    build date: 2015-05-08
    build time: 19:30:03
    build commit date: 2015-03-31
    build commit time: 13:39
    build hash: 000dfc0
    build platform: Linux
    build type: Release
    build c flags:  -Wall -Wcast-align -Werror=declaration-after-statement -Werror=implicit-function-declaration -Werror=return-type -Wstrict-prototypes -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wnonnull -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wuninitialized -Wredundant-decls -Wno-error=unused-but-set-variable -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4  -fopenmp  -msse2  -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing
    build c++ flags:  -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wuninitialized -Wundef -Wmissing-declarations -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4  -fopenmp  -msse2  -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing
    build link flags:  -Wl,--version-script=/build/blender/src/blender-2.74/source/creator/blender.map
    build system: CMake
```

_Edit_: Reversed back to the commit 5f319117951d9605ed62cdf0c9aebe025dedd972 and still works fine. Have not tried the inbetween versions.

**Comment by folkertdev** [comment]
The thing is that you need an up to date version of both the addon (this repo or current blender addons repo, both are the same file) and a recent blender source/build. 

as a side note (and I know that this is less of a problem on linux because of symlinks) don't forget to build the install target, which copies the API python files to the correct location (again this isn't necesarry if the /scripts folder is symlinked to the /2.74 folder)

hope that helps.
